### PR TITLE
Bitcode issue

### PR DESCRIPTION
**Pull request by yoalex5**
- `BITCODE_GENERATION_MODE` used-defined setting was added for PrebidMobile and core modules with `marker` by default
- `buildPrebidMobile` script was improved for asking about bitcode

### CODE REVIEW

**Comment by rakesthedon** [comment]
Why not just enable bitcode as a default and not go through the script? what is the advantages?

**Comment by yoalex5** [comment]
I want to propose a choice for consumers. If you decide not to use bitcode you should not edit script

**Comment by rakesthedon** [comment]
It is mandatory since iOS 10. i think this should be the enabled by default. most if not all third party framework are already enabling bitcode support.

**Comment by yoalex5** [comment]
@rakesthedon, can you point me out of the official resource about mandatory bitcode ?

I found next:
>For iOS apps, bitcode is the default, but optional. For watchOS and tvOS apps, bitcode is required.

https://help.apple.com/xcode/mac/current/#/devbbdc5ce4f

**Comment by rakesthedon** [comment]
It was my understanding but stand corrected. Can the default value be set to yes then?

**Comment by yoalex5** [comment]
done

**Comment by rakesthedon** [comment]
All that missing is the documentation update but it seems correct to me

**Review by ppuviarasu — APPROVED** [review]

**Pull request merged**
