### PR TITLE
Fix invalid stub for rubicon, and ensure correct prebid host in BidManagerTests.

### PR DESCRIPTION
**Pull request by SanderSander**
Currently the test `testRubiconBidManagerRequestForNoBidResponse` is failing silently, because the assertions pass when an invalid request is provided. 

Furthermore the tests can't be run individual because the default `PrebidHost` is custom (so empty, which results in an invalid host exception), but they succeed when executed in bulk/on travis because `Prebid.shared.prebidServerHost` is set in another test. 

This would make debugging easier!

### CODE REVIEW

**Comment by yoalex5** [comment]
Possibly is duplicated of #213

**Comment by SanderSander** [comment]
> Possibly is duplicated of #213

Yup you are right.

**Comment by yoalex5** [comment]
As for running tests in a random order the #200 was created. We need some time to fix it completely.

**Comment by SanderSander** [comment]
@yoalex5 

I ran all test separated, the only test outside `FetchingLogictest/BidManagerTests` is `PrebidTests::testServerCustomHost`

Where the first line is `XCTAssertEqual(Prebid.shared.prebidServerHost, PrebidHost.Appnexus)` 

A simple switch by testing in the first assert if the host is custom, and then set the host to Appnexus would do trick ;)

**Comment by bszekely1** [comment]
I am closing this issue since it's a duplicate of https://github.com/prebid/prebid-mobile-ios/pull/213.

@SanderSander, please review 213.

**Pull request closed without merging**
