### PR TITLE
Release script

### PR DESCRIPTION
**Pull request by ppuviarasu**

### CODE REVIEW

**Comment by yoalex5** [comment]
@ppuviarasu, are we going to integrate this functionality ?
What is the reason not using this script for deploying ?

**Comment by ppuviarasu** [comment]
The scripts create a universal framework of Prebid Mobile SDK that the publishers can integrate.

**Comment by yoalex5** [comment]
Do you plan to merge it to master branch ?

**Comment by ppuviarasu** [comment]
stale PR

**Pull request closed without merging**
