### PR TITLE
Support for First Party Data

### PR DESCRIPTION
**Pull request by yoalex5**
GitHub issue #181 

//ACL block
1. `Access Control List` 

`Targeting.shared` API

```
	func addBidderToAccessControlList(_ bidderName: String)
	func removeBidderFromAccessControlList(_ bidderName: String)
	func clearAccessControlList()
```

For Example

`	Targeting.shared.addBidderToAccessControlList(.bidderNameRubiconProject)`

will generate:

```
	"ext": {
		"prebid": {
			"data": {
				"bidders": [
					"rubicon"]
			}
		}
	}
```

//data block
2. `global user data`

`Targeting.shared` API

```
	func addUserData(key: String, value: String)
	func updateUserData(key: String, value: Set<String>) 
	func removeUserData(forKey: String)
	func clearUserData()
```

For example

`	Targeting.shared.addUserData(key: "globalUserDataKey1", value: "globalUserDataValue1")`

will generate:

```
	"user": {
		"ext": {
			"data": {
				"globalUserDataKey1": [
					"globalUserDataValue1"]
			}
		}
	}
```

3. `global context data`

`Targeting.shared` API

```
	func addContextData(key: String, value: String)
	func updateContextData(key: String, value: Set<String>)
	func removeContextData(forKey: String)
	func clearContextData()
```

For example

`	Targeting.shared.addContextData(key: "globalContextDataKey1", value: "globalContextDataValue1")`

will generate:

```
	"app": {
		"ext": {
			"data": {
				"globalContextDataKey1": [
					"globalContextDataValue1"]
			}
		}
	}
```

4. `adunit context data`

`AdUnit` API

```
	func addContextData(key: String, value: String)
	func updateContextData(key: String, value: Set<String>)
	func removeContextData(forKey: String)
	func clearContextData()
```

For example

`	bannerAdUnit.addContextData(key: "adunitContextDataKey1", value: "adunitContextDataValue1")`

will generate:

```
	"imp": [{
		"ext": {
			"context": {
				"data": {
					"adunitContextDataKey1": [
						"adunitContextDataValue1"]
				}
			}
		}
	}]
```

5. `global context keywords`

`Targeting.shared` API

```
	func addContextKeyword(_ newElement: String)
	func addContextKeywords(_ newElements: Set<String>)
	func removeContextKeyword(_ element: String)
	func clearContextKeywords() 
```

For example

```
        Targeting.shared.addContextKeyword("globalContextKeywordValue1")
        Targeting.shared.addContextKeyword("globalContextKeywordValue2")
        Targeting.shared.addContextKeyword("globalContextKeywordValue3")
```

will generate:

```
	"app": {
	    "keywords": "globalContextKeywordValue1,globalContextKeywordValue2,globalContextKeywordValue3"
	}

```
6. `global user keywords`

`Targeting.shared` API

```
	func addUserKeyword(_ newElement: String)
	func addUserKeywords(_ newElements: Set<String>)
	func removeUserKeyword(_ element: String)
	func clearUserKeywords()
```

For example

```
        Targeting.shared.addUserKeyword("globalUserKeywordValue1")
        Targeting.shared.addUserKeyword("globalUserKeywordValue2")
        Targeting.shared.addUserKeyword("globalUserKeywordValue3")
```

will generate:

```
	"user": {
	    "keywords": "globalUserKeywordValue1,globalUserKeywordValue2,globalUserKeywordValue3"
	}
```

7. `adunit context keywords`

`AdUnit` API

```
	func addContextKeyword(_ newElement: String)
	func addContextKeywords(_ newElements: Set<String>)
	func removeContextKeyword(_ element: String)
	func clearContextKeywords()
```

For example

```
    bannerAdUnit.addContextKeyword("adunitContextKeywordValue1")
    bannerAdUnit.addContextKeyword("adunitContextKeywordValue2")
    bannerAdUnit.addContextKeyword("adunitContextKeywordValue3")
```
    
will generate:

```
	"imp": [{
	    "ext": {
	        "context": {
	            "keywords": "adunitContextKeywordValue1,adunitContextKeywordValue2,adunitContextKeywordValue3"
	        }
	    }
	}]
```

[all_changes_are_included_2.chls.zip](https://github.com/prebid/prebid-mobile-ios/files/3134073/all_changes_are_included_2.chls.zip)

### CODE REVIEW

**Comment by yoalex5** [comment]
@ppuviarasu Have you had a chance to review this feature ?

**Comment by ppuviarasu** [comment]
Also this PR has merge conflicts. do resolve the same and request for review

**Comment by yoalex5** [comment]
@ppuviarasu, I have removed PBMViewTool changes and  created issue #225. Merge conflicts were solved

**Comment by yoalex5** [comment]
@ppuviarasu, I have fixed conflicts, could you please check it ?

**Pull request merged**
