### PR TITLE
Carthage support

### PR DESCRIPTION
**Pull request by akkrat**
Carthage support #245 

Deintegrate pods from main project.
Fix linter warnings.
Add carthage support.
Fix examples and travis build script.
Add carthage example.
Update readme.

### CODE REVIEW

**Comment by yoalex5** [comment]
Hello @akkrat 
Thanks for your PR

1. Is it possible to move all linter warnings into a separate PR since there are a lot of files that are not relevant to Cartage support ?
2. Why did you divide `Prebid Demo` and `Prebid Mobile` ? As an SDK developer I would like to have a single workspace to work with all projects simultaneously 
3. When I run `carthage update` I get `Build Failed - Task failed with exit code 65`

**Comment by akkrat** [comment]
Hello @yoalex5 
1. I've removed them for now
2. Seems like i failed to do it with locally corrupted workspace 😢 . Fixed
3. You need update Cartfile for testing:
```
github "https://github.com/akkrat/prebid-mobile-ios.git" "carthage-support"
```

**Comment by yoalex5** [comment]
Hello @akkrat 

Could you please take a look at #277?

Thanks

**Comment by bszekely1** [comment]
This PR is being closed in favor of https://github.com/prebid/prebid-mobile-ios/pull/277

**Pull request closed without merging**
