### PR TITLE
[API 1.0] [MoPub] Banner ad is not rendered properly

### PR DESCRIPTION
**Pull request by yoalex5**
Fix for issue https://github.com/prebid/prebid-mobile-ios/issues/150

### CODE REVIEW

**Comment by yoalex5** [comment]
@ppuviarasu will this PR supposed to be merged in the master ?

**Comment by ppuviarasu** [comment]
I am waiting for the tests to be completed and the button enabled. Once we have that we can merge to master

**Comment by yoalex5** [comment]
thanks

Also is it possible to have a permission to push to the repository? 
Because now I have to make a PR using forked repository

**Comment by yoalex5** [comment]
Hello @ppuviarasu 

Have the tests been passed and is it possible to merge the PR ?

**Comment by ppuviarasu** [comment]
Can you pull the latest master and makesure there are no merge conflicts? This branch is not enabled for merging

**Comment by yoalex5** [comment]
Okay, I will do it

Thanks

**Comment by yoalex5** [comment]
I had to create a new PR because this one was created via github editing tool so it is not possible to update this one

@ppuviarasu Could you please approve the duplicated PR
https://github.com/prebid/prebid-mobile-ios/pull/156

**Pull request closed without merging**
