### PR TITLE
Rearchitect multi module structure

### PR DESCRIPTION
**Pull request by yoalex5**
main changes:

- Rearchitect multi module structure (#368)
- XCFramework is used instead of UniversalFramework(#369)
- Swift Package Manager(SPM) support(#345)
- Carthage support without extra scripts
- Stared test source files were moved into a separate project - `TestUtils`
- all targets of PrebidMobile project are located in the root folder
- minor changes(#377)

### CODE REVIEW

**Review by YuriyVelichkoOpenX — COMMENTED** [review]
Hi everyone! I did not have much time today for a deep review, so I'm still in progress with this.

However, I would like to clarify that after this PR we will get one module for all integration kinds instead of improving the granularity of modules. Therefore publishers who want to integrate the prebid SDK only for in-stream video will get all other ad formats as well in the framework. Is it an intended future behavior or just an intermediated step of the modularization initiative? 

Which modules are you going to get in the result of modularization?

**Comment by yoalex5** [comment]
> I would like to clarify that after this PR we will get one module for all integration kinds instead of improving the granularity of modules. 

The main target of this PR is to get rid of using single module name for all modules in future

> Therefore publishers who want to integrate the prebid SDK only for in-stream video will get all other ad formats as well in the framework.

Current module includes all ad formats (Banner, Interstitial, Video) inside corresponding `AdUnit` successors (BannerAdUnit, InterstitialAdUnit, VideoAdUnit...) which allows publishers to make auction request in a simple manner. In my opinion all these classes solve a single task - provide publisher a winning bid. I don't think that this module should be divided into smaller modules because these classes are not heavy and do not have others dependencies

>  Is it an intended future behavior or just an intermediated step of the modularization initiative?

It is expected behaviour. At least for now

**Comment by bszekely1** [comment]
It is for this reason we would need a module overview page and a description of the module architecture. By default Prebid SDK has minimal logic. As we add more complex functionality and additional weight as Oleksandr has pointed out, we can break them out as modules.

**Comment by YuriyVelichkoOpenX** [comment]
@yoalex5 @bszekely1 thanks for the clarification. Everything sounds reasonable. And yes we definitely need a precise overview of modularisation.

**Review by YuriyVelichkoOpenX — DISMISSED** [review]
LGTM

**Comment by yoalex5** [comment]
@YuriyVelichkoOpenX, could you please check my latest commits. 
I added `TestUtils` module

**Comment by YuriyVelichkoOpenX** [comment]
@yoalex5, the new module looks good!

However, I can't run unit tests nor from Xcode nor from script:

image

image

**Comment by yoalex5** [comment]
@YuriyVelichkoOpenX 

Could you please remove `Derived Data` folder and build a test target ?
CI does not have such problem

**Comment by YuriyVelichkoOpenX** [comment]
@yoalex5 , cleaning of Derived Data didn't help but rebooting helped. 

Everything works!

**Review by YuriyVelichkoOpenX — APPROVED** [review]
LGTM

**Pull request merged**
