### PR TITLE
Enabling Prebid Carthage integration for PrebidMobile framework without the script

### PR DESCRIPTION
**Pull request by rakesthedon**
Hi!

This will in my opinion make the use of carthage more inline with how it is suppose to work.

Advantages:
- Simplify carthage usage
- ~~No need for a script~~
- Better CI for people using carthage

Disadvantages:
- Both framework will be build even if only one is needed.

### CODE REVIEW

**Comment by yoalex5** [comment]
Hello @rakesthedon 

We use workspace for developing(framework)/testing(tests)/using(apps) PrebidSDK
1. Since you removed a lot of schemas it is impossible to do it
2. If you run `carthage update` you get
```
*** Fetching prebid-mobile-ios
*** Checking out prebid-mobile-ios at "f8719a221ac064883d76f1ba419b77411676971d"
*** xcodebuild output can be found in /var/folders/2q/jhrcxkmx49g21lydqfrf26ph0000gn/T/carthage-xcodebuild.SBP8VJ.log
*** Building scheme "PrebidMobile" in PrebidMobile.xcworkspace
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/alex/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/prebid-mobile-ios/f8719a221ac064883d76f1ba419b77411676971d/Build/Intermediates.noindex/ArchiveIntermediates/PrebidMobile/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/PrebidMobile.framework/PrebidMobile /Users/alex/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/prebid-mobile-ios/f8719a221ac064883d76f1ba419b77411676971d/Build/Products/Release-iphonesimulator/PrebidMobile.framework/PrebidMobile -output /Users/alex/Downloads/SomeExperiments/Carthage/Build/iOS/PrebidMobile.framework/PrebidMobile

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/2q/jhrcxkmx49g21lydqfrf26ph0000gn/T/carthage-xcodebuild.SBP8VJ.log
```

**Comment by rakesthedon** [comment]
1. The scheme are not removed i just disabled the shared attribute. 
2. The issue that you are talking about is not related to the PR it is an issue with XCode 12 => https://github.com/Carthage/Carthage/issues/3019

**Comment by yoalex5** [comment]
How I can enable them ? For example PrebidDemoSwift or PrebidDemoObjectiveC 
Screenshot 2021-04-05 at 16 25 03

**Comment by rakesthedon** [comment]
I found the issue and I'll close this PR. I've managed to fix the issue in another branch

**Review by Pornprasert — COMMENTED** [review]
****

**Pull request closed without merging**
