### PR TITLE
feat: added support to be able to use the cocoapods dependency without having the use_framework flag

### PR DESCRIPTION
**Pull request by jovencinho**

### CODE REVIEW

**Review by OlenaPostindustria — APPROVED** [review]
LGTM

**Comment by OlenaPostindustria** [comment]
These changes require setting development team for `PrebidSDKCoreResources`.
image

**Comment by YuriyVelichkoPI** [comment]
I created a test project and put the next line into Podfile

```
  pod 'PrebidMobile', :path => '/Users/yuriy/Downloads/prebid-mobile-ios-feat-not_use_frameworks_compatibility'
```

Building the project without `use_frameworks!` I see errors like this  

```
Module map file '/Users/yuriy/Library/Developer/Xcode/DerivedData/test_prebid_pods-eauaglnpngkcbodgzlgigzifbtbp/Build/Products/Debug-iphonesimulator/PrebidMobile/PrebidMobile.modulemap' not found

```

I removed the mention of `PrebidMobile.modulemap` in the Build Setting if the PrebidMobile target under the Pods but without success. 

Also, I see PrebidMobile.modulemap in the next places of the test  project 

image

Is it expected with using local podspec?  What should I do to test the new podspec properly?

**Comment by YuriyVelichkoPI** [comment]
nevermind, cleaning the caches solves the build issue on my side

**Pull request merged**
