### PR TITLE
Set inventory

### PR DESCRIPTION
**Pull request by AntoineJac**
here is the feature request: #165

### CODE REVIEW

**Comment by ppuviarasu** [comment]
The changes are approved. Need the changes in Android too for us to merge and do a new release to maven & cocoapods. Will keep it open until we have the android changes and push to master when both are complete

**Comment by AntoineJac** [comment]
@ppuviarasu , thanks will do the change for Android next week. There are a few points that need to be fixed also for the Android version.
Will post the Android PR has soon as I have completed all tests.
Thanks,

**Comment by ppuviarasu** [comment]
resolve the conflict & submit the PR

**Comment by ppuviarasu** [comment]
@AntoineJac The user keywords were intentionally set per adUnit and is explicitly mentioned in out I2I
https://github.com/prebid/prebid-mobile-ios/issues/113
The reasoning if the publisher wants to set only for a specific adUnit n not for others.
The implementation was done as mentioned.
Lets keep it that level and continue the same.

**Comment by AntoineJac** [comment]
Thanks all, let stall this until #165 has been validated and a intent to implement decided.

**Comment by AntoineJac** [comment]
will use the new api for passing data

**Pull request closed without merging**
