### PR TITLE
Enabling Prebid Carthage integration for PrebidMobile framework

### PR DESCRIPTION
**Pull request by rakesthedon**
Hi!

This will in my opinion make the use of carthage more inline with how it is suppose to work.

Advantages:
- Simplify carthage usage
- Better CI for people using carthage
Disadvantages:
- Both framework will be build even if only one is needed.

### CODE REVIEW

**Comment by yoalex5** [comment]
Hello @rakesthedon 
I still see a simple framework

Screenshot 2021-04-06 at 11 20 11

**Comment by rakesthedon** [comment]
since both framework have the same name when they are built one is overriding the other, that can be fix if we change the name of the product name of PrebidMobileCore to PrebidMobileCore.framework

**Comment by yoalex5** [comment]
I have already mentioned this behaviour in
https://github.com/prebid/prebid-mobile-ios/pull/372#issuecomment-813392180

Technically product name should be the same as module name. That is why you can not have different product names with the same module name

**Comment by rakesthedon** [comment]
My bad i didn't see that part, but may i ask why? I don't think this a common convention. What was the decision factor for this decision?

**Comment by yoalex5** [comment]
Main reason was to reusing modules. Publisher can switch(add/remove) between different modules without updating class files

Now we are discussing a possibility to rearchitect modules #368

**Comment by rakesthedon** [comment]
I see. Then may be it is too early for this PR then.

**Pull request closed without merging**
