### PR TITLE
Fixing "version" value in the auction request

### PR DESCRIPTION
**Pull request by yoalex5**
GitHub isuue #203

### CODE REVIEW

**Comment by yoalex5** [comment]
@ppuviarasu, could you please review this PR ?

**Comment by ppuviarasu** [comment]
We did a release without this 😢 
Can you check if you can revert the cocoapods push and do with the new one

**Comment by yoalex5** [comment]
@bszekely1, what do you think about it ?

**Comment by bszekely1** [comment]
Lets re-release this. It's typically not good practice to add items after release, however we are very close to release time and developers are not rushing to download right away. 

Please perform another release with the same tag as soon as possible. It will be included in 1.1

**Pull request merged**
