### PR TITLE
Fixing Unit tests

### PR DESCRIPTION
**Pull request by yoalex5**
GitHub issue #212

### CODE REVIEW

**Comment by yoalex5** [comment]
@ppuviarasu, could you please review this PR ?

**Comment by yoalex5** [comment]
The last commit should fix #200

**Comment by ppuviarasu** [comment]
does both these PR have the same set of changes https://github.com/prebid/prebid-mobile-ios/pull/221/files

**Comment by yoalex5** [comment]
It seems so

**Comment by yoalex5** [comment]
All these changes is a part of #213

**Pull request closed without merging**
