### PR TITLE
Adapt resize feature for Objective-C client

### PR DESCRIPTION
**Pull request by yoalex5**
GitHub issue #215

What were changed:
1. `Utils.shared` was opened for Objective-C
2. A new method `AdViewUtils.findPrebidCreativeSize` was created to support `success` and `failure` handlers: 
3. The old resize function(`
findPrebidCreativeSize(_:success:)`) was marked as deprecated and it's still possible to use it (to support compatibility)

Screen Shot 2019-07-04 at 11 06 13 PM

4. Demo apps for Swift and Objective-C were updated to use the new function

The latest API for resize function looks like

Swift:
```
    func adViewDidReceiveAd(_ bannerView: GADBannerView) {
        print("adViewDidReceiveAd")

        AdViewUtils.findPrebidCreativeSize(bannerView,
                                            success: { (size) in
                                                guard let bannerView = bannerView as? DFPBannerView else {
                                                    return
                                                }

                                                bannerView.resize(GADAdSizeFromCGSize(size))

        },
                                            failure: { (error) in
                                                print("error: \(error)");

        })
}
```

Objective-C:
```
-(void) adViewDidReceiveAd:(GADBannerView *)bannerView {
    NSLog(@"Ad received");
    [AdViewUtils findPrebidCreativeSize:bannerView
                                   success:^(CGSize size) {
                                       if ([bannerView isKindOfClass:[DFPBannerView class]]) {
                                           DFPBannerView *dfpBannerView = (DFPBannerView *)bannerView;
                                           
                                           [dfpBannerView resize:GADAdSizeFromCGSize(size)];
                                       }
                                   } failure:^(NSError * _Nonnull error) {
                                       NSLog(@"error: %@", error);
                                   }];
}

```

Error codes:
```
unspecifiedCode = 101
noWebViewCode = 110
uiWebViewFailedCode = 121
wkWebViewFailedCode = 126
noHtmlCode = 130
noSizeObjectCode = 140
noSizeValueCode = 150
sizeUnparsedCode = 160
```

What to do:
1. Update docs

### CODE REVIEW

**Comment by ptomasroos** [comment]
Great improvement!

**Comment by yoalex5** [comment]
Today I will update this PR

**Comment by yoalex5** [comment]
I am working on some minor changes

**Comment by yoalex5** [comment]
Hello @ppuviarasu 

Thank you for review

>The AdViewUtils primarily deals with only the size manipulations... We can give a more meaningful name to the same

I proposed this API because in future we will have a possibility to add additional public utility functions for working with AdView

**Pull request merged**
