### PR TITLE
Video format support

### PR DESCRIPTION
**Pull request by yoalex5**
GitHub issue #232 

**Out-Stream Video**
API
```Swift
VideoAdUnit(configId: "1001_test_video", size: CGSize(width: 640, height: 480))
```

PBVideoAdDelegate
```
func videoAd(event: PBVideoAdEvent)
```

PBVideoAdEventType
```
AdLoadSuccess
AdLoadFail
AdClicked
AdStarted
AdDidReachEnd
```

**InterstitialVideo**
API

```Swift
VideoInterstitialAdUnit(configId: "1001_test_video", size: CGSize(width: 640, height: 480))
```

PBVideoAdInterstitialDelegate
```
func videoAdInterstitialLoaded()
func videoAdInterstitialCancelled()
func videoAdInterstitialCompleted()
func videoAdInterstitialFailed()
func videoAdInterstitial(event: PBVideoAdEvent)
```

OpennRTB request:
``` JSON
{
    "imp": [{
        "video": {
            "w": 640,
            "h": 480,
            "startdelay": 0,
            "protocols": [7],
            "playbackmethod": [2],
            "mimes": ["video/mp4"]
        },
    }],
    "ext": {
        "prebid": {
            "cache": {
                "vastxml": {}
            },
        },
    },
    "instl": 1 <--Only for Interstitial-->
}

```

- video-ima module was created

### CODE REVIEW

**Comment by eros902002** [comment]
@yoalex5 Do we know why Travis CI is not building?

**Comment by yoalex5** [comment]
@eros902002 , I will check and fix

**Comment by yoalex5** [comment]
@eros902002 , TravisCI was fixed

**Comment by ppuviarasu** [comment]
Is this only outstream & not instream is it?

**Comment by yoalex5** [comment]
@ppuviarasu, correct. There are no In-Stream code

**Comment by bszekely1** [comment]
We are not using IMA SDK any longer. This PR is outdated.

**Pull request closed without merging**
