### PR TITLE
Utils class improvements

### PR DESCRIPTION
**Pull request by Gaetan**
Formatted the Utils class.

Reworked the `findPrebidCreativeSize` method to have a success and failure handler. The method will always call one or the other.

In case of an error, the error message will be logged and passed to the failure handler.

### CODE REVIEW

**Comment by yoalex5** [comment]
Hello @Gaetan!

Thanks for contributing. 
I have already fixed the bug with handler and it will be a part of #216 PR. Also this PR will include some internal improvements.

1. Could you please exclude refactoring changes
2. Have these changes fixed problems with random returns and empty blank ad as you described in a letter?

Thank you

**Comment by Gaetan** [comment]
Hi @yoalex5,

The goal of this PR is to mainly share my vision on how I expect the `findPrebidCreativeSize` to work. I can adapt it in case you see value in the changes.

You say that #216 will include some internal improvements, does that mean that you are going to make additional changes to that PR?

1. The refactoring changes I propose here go a bit further than #216, there you would only get a message "cannot get size" in case of a failure. With my changes you can expect messages like:
 - "subView doesn't include WebView"
- "jsCode is nil"
- "Size cannot be parsed"
These messages should help the app developers to pin point what they are doing wrong.

Also at the moment, if the view does not contain a webview, the handler is not called. [Utils.swift#L108](https://github.com/prebid/prebid-mobile-ios/blob/a20e582b894ae97e4020e9fdd254585f10f7f7b7/src/PrebidMobile/PrebidMobile/AdUnits/Utils.swift#L108)
If the javascript execution in the webview fails, the handler is not called: [Utils.swift#L140](https://github.com/prebid/prebid-mobile-ios/blob/a20e582b894ae97e4020e9fdd254585f10f7f7b7/src/PrebidMobile/PrebidMobile/AdUnits/Utils.swift#L140)

2. These changes should allow us to pin point the problem we are facing. I will keep you up to date if we make progress.

Kind regards,

Gaetan

**Comment by yoalex5** [comment]
I will merge your changes into my branch and after that I will propose it on review

**Comment by yoalex5** [comment]
@Gaetan 

I have updated [the PR](https://github.com/prebid/prebid-mobile-ios/pull/216#commits-pushed-8ecf2d7) by your changes

**Comment by Gaetan** [comment]
@yoalex5 Thank you, I will close this PR then.

**Pull request closed without merging**
